[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["weavingspace", "."]
exclude = ["superseded"]

[project]
name = "weavingspace"
version = "0.0.7.97"
authors = [
  { name="David O'Sullivan", email="osullivan512@gmail.com" },
]
description = "A package for making tiled mapping layers"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
# dependency minimum versions set for compatibility with pyodide
dependencies = [
    "dataclasses>=0.8",
    "typing>=3.10.0.0",
    "matplotlib>=3.8.4",
    "pandas>=2.2.3",
    "shapely>=2.0.6",
    "fiona>=1.9.5",
    "geopandas>=1.0.1",
    "mapclassify>=2.10.0",
    "networkx>=3.5",
]

[project.urls]
Homepage = "https://github.com/DOSull/weavingspace"
Repository = "https://github.com/DOSull/weavingspace"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "SLF001",
  "PLR2004",
  "RUF007",
  "N802",
  "N803",
  "N806",
  "N815",
  "FBT001",
  "FBT002",
  "TC002",
  "T201",
  "D105"
]

[tool.ruff]
line-length = 80